/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.db.mixing;

/**
 * Marker exception to make which field produced an error.
 * <p>
 * This is used as "cause" for <tt>HandledExceptions</tt> that are generated by a failed field check.
 * This way, other frameworks can pick up this exception and extract the source field for an error message.
 * <p>
 * This is used by sirius-biz to highlight the field which caused an error when trying to saven an entity.
 */
public class InvalidFieldException extends Exception {

    private String field;

    /**
     * Creates a new exception for the given field.
     *
     * @param field the name of the field which produced the error message
     */
    public InvalidFieldException(String field) {
        super(field);
        this.field = field;
    }

    public String getField() {
        return field;
    }
}
