/*
 * Made with all the love in the world
 * by scireum in Remshalden, Germany
 *
 * Copyright by scireum GmbH
 * http://www.scireum.de - info@scireum.de
 */

package sirius.db.mixing.query;

import sirius.db.mixing.EntityDescriptor;
import sirius.db.mixing.query.constraints.Constraint;
import sirius.db.mixing.query.constraints.FilterFactory;
import sirius.kernel.di.std.Named;

/**
 * Compiles a tag value provided by a {@link QueryTag} into a {@link Constraint}.
 *
 * @param <C> the type of constraints generated by this handler
 */
public interface QueryTagHandler<C extends Constraint> extends Named {

    /**
     * Computes the constraint.
     *
     * @param descriptor the entity for which the constraint is to be created
     * @param tagValue   the value to filter on
     * @return a constraint representing the given filter
     */
    C generateConstraint(FilterFactory<C> factory, EntityDescriptor descriptor, String tagValue);
}
